#!/usr/bin/env node
/**
 * build-members.mjs - turn the Discord bot's wallet exports into a wallet ->
 * name map the dashboard can use, and report who is still anonymous.
 *
 * The names live in the fractal Discord bot repo, not here. Point the script at
 * that repo's data/ directory (default: ../fractalbotjuly2026/data, override
 * with MEMBER_SOURCE_DIR). Three files matter:
 *
 *   names_to_wallets.json  display name -> wallet, the primary map
 *   wallets.json           discord user id -> wallet
 *   history.json           breakout rankings, which carry discord id -> display
 *                          name and so name the wallets.json-only entries
 *
 * Writes data/members.json and rewrites the KNOWN_MEMBERS block in
 * dao/src/lib/constants.ts. Run scripts/pull-data.mjs first - the on-chain
 * snapshot is what tells us which names actually correspond to holders.
 *
 * Usage:  node scripts/build-members.mjs [--dry-run]
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(ROOT, 'data');
const CONSTANTS = join(ROOT, 'dao', 'src', 'lib', 'constants.ts');

const SOURCE_DIR = resolve(
  process.env.MEMBER_SOURCE_DIR || join(homedir(), 'Desktop', 'repos', 'fractalbotjuly2026', 'data'),
);

/** The bot exports carry a couple of names whose spelling is fixed by the ZAO
 * brand glossary. Corrected on the way out; the export itself is untouched. */
const BRAND_SPELLING = {
  'dan singjoy': 'Dan SingJoy',
  'jose (joesph goats)': 'Jose (Joseph Goats)',
};
const brandName = (name) => BRAND_SPELLING[name.toLowerCase()] ?? name;

const readJson = async (path) => JSON.parse(await readFile(path, 'utf8'));
const isAddress = (v) => typeof v === 'string' && /^0x[0-9a-fA-F]{40}$/.test(v);

async function loadNames() {
  if (!existsSync(SOURCE_DIR)) {
    throw new Error(`member source dir not found: ${SOURCE_DIR}\nSet MEMBER_SOURCE_DIR to the fractal bot's data/ directory.`);
  }
  const [namesToWallets, wallets, history] = await Promise.all([
    readJson(join(SOURCE_DIR, 'names_to_wallets.json')),
    readJson(join(SOURCE_DIR, 'wallets.json')).catch(() => ({})),
    readJson(join(SOURCE_DIR, 'history.json')).catch(() => ({ fractals: [] })),
  ]);

  // address -> { name, source }. First writer wins, so the explicit
  // name-to-wallet map beats anything reconstructed from rankings.
  const byAddress = new Map();
  const add = (address, name, source) => {
    if (!isAddress(address) || !name) return;
    const key = address.toLowerCase();
    if (byAddress.has(key)) return;
    byAddress.set(key, { address: key, name: brandName(String(name).trim()), source });
  };

  for (const [name, address] of Object.entries(namesToWallets)) {
    add(address, name, 'names_to_wallets.json');
  }

  const discordNames = new Map();
  for (const fractal of history.fractals || []) {
    for (const r of fractal.rankings || []) {
      if (r.user_id && r.display_name) discordNames.set(String(r.user_id), r.display_name);
    }
  }
  for (const [discordId, address] of Object.entries(wallets)) {
    add(address, discordNames.get(String(discordId)), 'history.json + wallets.json');
  }

  const unmapped = Object.entries(namesToWallets)
    .filter(([, address]) => !isAddress(address))
    .map(([name]) => name)
    .sort();

  return { byAddress, unmapped };
}

/** Cross-reference the names against the on-chain snapshot so the output says
 * who actually holds Respect, and who on chain is still nameless. */
async function loadOnChain() {
  const holders = new Map();
  const bump = (address, patch) => {
    const key = address.toLowerCase();
    holders.set(key, { address: key, zorRespect: 0, zorAwards: 0, ogRespect: 0, ...holders.get(key), ...patch });
  };
  try {
    for (const h of (await readJson(join(DATA, 'zor-respect.json'))).holders) {
      bump(h.address, { zorRespect: h.respect, zorAwards: h.awards });
    }
  } catch { /* pull-data has not run for ZOR yet */ }
  try {
    for (const h of (await readJson(join(DATA, 'og-respect.json'))).holders) {
      bump(h.address, { ogRespect: h.respect });
    }
  } catch { /* pull-data has not run for OG yet */ }
  return holders;
}

function renderKnownMembers(members) {
  const rows = members
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name, 'en', { sensitivity: 'base' }))
    .map((m) => `  '${m.address}': '${m.name.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`)
    .join('\n');
  return [
    '// Wallet -> display name, generated by scripts/build-members.mjs from the',
    '// fractal Discord bot exports. Keys are lowercase; displayName() in',
    '// format.ts lowercases before lookup. Do not hand-edit - rerun the script.',
    'export const KNOWN_MEMBERS: Record<string, string> = {',
    rows,
    '};',
  ].join('\n');
}

async function patchConstants(members) {
  const src = await readFile(CONSTANTS, 'utf8');
  const start = src.indexOf('export const KNOWN_MEMBERS');
  if (start === -1) throw new Error('KNOWN_MEMBERS not found in dao/src/lib/constants.ts');
  const end = src.indexOf('};', start);
  if (end === -1) throw new Error('KNOWN_MEMBERS block is not terminated');

  // Swallow the hand-written comment block directly above the declaration.
  let head = src.slice(0, start);
  const lines = head.split('\n');
  while (lines.length && (lines.at(-1).trimStart().startsWith('//') || lines.at(-1).trim() === '')) lines.pop();
  head = lines.join('\n') + '\n\n';

  await writeFile(CONSTANTS, head + renderKnownMembers(members) + src.slice(end + 2));
}

async function main() {
  const dryRun = process.argv.includes('--dry-run');
  const { byAddress, unmapped } = await loadNames();
  const onChain = await loadOnChain();

  const members = [...byAddress.values()].map((m) => {
    const chain = onChain.get(m.address);
    return {
      ...m,
      holder: Boolean(chain),
      zorRespect: chain?.zorRespect ?? 0,
      zorAwards: chain?.zorAwards ?? 0,
      ogRespect: chain?.ogRespect ?? 0,
    };
  }).sort((a, b) => (b.zorRespect + b.ogRespect) - (a.zorRespect + a.ogRespect) || a.name.localeCompare(b.name));

  const unnamed = [...onChain.values()]
    .filter((h) => !byAddress.has(h.address))
    .sort((a, b) => (b.zorRespect + b.ogRespect) - (a.zorRespect + a.ogRespect));

  const out = {
    generatedAt: new Date().toISOString(),
    source: SOURCE_DIR,
    counts: {
      named: members.length,
      namedAndHolding: members.filter((m) => m.holder).length,
      onChainHolders: onChain.size,
      onChainUnnamed: unnamed.length,
      namesWithoutWallet: unmapped.length,
    },
    members,
    unnamedHolders: unnamed,
    namesWithoutWallet: unmapped,
  };

  console.log(JSON.stringify(out.counts, null, 2));
  if (dryRun) return;

  await writeFile(join(DATA, 'members.json'), JSON.stringify(out, null, 2) + '\n');
  console.log('wrote data/members.json');
  await patchConstants(members.filter((m) => m.holder));
  console.log('patched dao/src/lib/constants.ts');
}

main().catch((err) => {
  console.error('build-members failed:', err.message);
  process.exit(1);
});
